#!/bin/sh

# Warning: VERY similar to render_today
# TODO take argument [today|full]

ls -1tr snaps/*.png > /tmp/frames_full.txt && \
mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell:autoaspect:vqscale=3 -vf \
scale=1280:720 -mf \
type=png:fps=25 \
mf://@/tmp/frames_full.txt \
-o videos/full.avi
