#!/bin/sh
find snaps/*.png -newermt $(date -d today +%Y-%m-%d) > /tmp/frames.txt && \
mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell:autoaspect:vqscale=3 -vf \
scale=1280:720 -mf \
type=png:fps=25 \
mf://@/tmp/frames.txt \
-o videos/$(date -d today +%Y-%m-%d).avi
